### ISSUE TITLE
Get this added to the official srcery org?

### ISSUE THREAD

**Issue by hermitmaster** [nils-degroot/srcery-intellij#1]
Great work! I've been waiting for someone to port this for quite a while. Perhaps see if it can be added to the official https://github.com/srcery-colors org?

**Comment by nils-degroot** [comment]
Hi there. I created a pull request at the srcery-gui repository. You can find it here https://github.com/srcery-colors/srcery-gui/pull/13.

**Comment by nils-degroot** [comment]
It has its own repository now. You can find it here https://github.com/srcery-colors/srcery-intellij.
